-- Users Table
-- Stores both students (who interact via SMS/Web) and teachers (who use the grading app)
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    role TEXT NOT NULL CHECK (role IN ('student', 'teacher', 'admin')),
    name TEXT NOT NULL,
    phone_number TEXT UNIQUE, -- Useful for SMS/USSD learning loop
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Lessons/Content Table
-- Stores the metadata for the offline PDFs, videos, or SMS riddles hosted on the node
CREATE TABLE IF NOT EXISTS lessons (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    content_type TEXT NOT NULL CHECK (content_type IN ('pdf', 'video', 'sms_riddle')),
    file_path TEXT, -- Nullable, used if the content is a file on the Raspberry Pi
    sms_content TEXT, -- Nullable, used if the content is an SMS riddle
    difficulty_level INTEGER DEFAULT 1, -- To generate the student's next lesson based on progress
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Assignments Table
-- Links a student to a specific lesson that they need to complete or have completed
CREATE TABLE IF NOT EXISTS assignments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER NOT NULL,
    lesson_id INTEGER NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'completed')),
    assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users (id),
    FOREIGN KEY (lesson_id) REFERENCES lessons (id)
);

-- Submissions Table
-- Stores the grades after the Edge AI app scans the physical paper
CREATE TABLE IF NOT EXISTS submissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    assignment_id INTEGER NOT NULL,
    teacher_id INTEGER NOT NULL, -- The teacher who scanned the document
    scanned_text TEXT, -- The raw text output from the on-device OCR
    grade INTEGER, -- e.g., the 2-mark or 5-mark rubric mentioned in the brief
    feedback TEXT, -- Optional feedback generated by the local AI logic
    submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (assignment_id) REFERENCES assignments (id),
    FOREIGN KEY (teacher_id) REFERENCES users (id)
);
