-- Users Table
-- Stores both students (who interact via SMS/Web) and teachers (who use the grading app)
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    role TEXT NOT NULL CHECK (role IN ('student', 'teacher')),
    name TEXT NOT NULL,
    phone_number TEXT UNIQUE, -- Useful for SMS/USSD learning loop
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Classes Table (e.g., Grade 1, Grade 2)
CREATE TABLE IF NOT EXISTS classes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    level INTEGER NOT NULL UNIQUE,
    name TEXT NOT NULL
);

-- Subjects Table (e.g., Math for Grade 1)
CREATE TABLE IF NOT EXISTS subjects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    class_id INTEGER NOT NULL,
    FOREIGN KEY (class_id) REFERENCES classes (id)
);

-- Chapters Table (e.g., Fractions for Math)
CREATE TABLE IF NOT EXISTS chapters (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    subject_id INTEGER NOT NULL,
    FOREIGN KEY (subject_id) REFERENCES subjects (id)
);

-- Topics/Content Table (Replacing the old "Lessons" table)
CREATE TABLE IF NOT EXISTS topics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    chapter_id INTEGER NOT NULL,
    content_type TEXT NOT NULL CHECK (content_type IN ('pdf', 'video', 'sms_riddle')),
    file_path TEXT, -- Nullable, used if the content is a file on the Raspberry Pi
    sms_content TEXT, -- Nullable, used if the content is an SMS riddle
    FOREIGN KEY (chapter_id) REFERENCES chapters (id)
);

-- Assignments Table
-- Links a student to a specific topic that they need to complete or have completed
CREATE TABLE IF NOT EXISTS assignments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER NOT NULL,
    topic_id INTEGER NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'completed')),
    assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users (id),
    FOREIGN KEY (topic_id) REFERENCES topics (id)
);

-- Submissions Table
-- Stores the grades after the Edge AI app scans the physical paper
CREATE TABLE IF NOT EXISTS submissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    assignment_id INTEGER NOT NULL,
    teacher_id INTEGER NOT NULL, -- The teacher who scanned the document
    grade INTEGER, -- e.g., the 2-mark or 5-mark rubric mentioned in the brief
    feedback TEXT, -- Optional feedback generated by the local AI logic
    submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (assignment_id) REFERENCES assignments (id),
    FOREIGN KEY (teacher_id) REFERENCES users (id)
);
